spring:
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
  datasource-postgres:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:5432/db_cda
    username: 'postgres'
    password: 'postgres'
    platform: postgresql
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 10
      minimum-idle: 5
      pool-name: ReadHikariPool

  datasource-mysql:
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/db_cda?nullCatalogMeansCurrent=false
    username: 'root'
    password: 'root'
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 10
      minimum-idle: 5
      pool-name: WriteHikariPool


